name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, 386]

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.x'
        architecture: ${{ matrix.arch }}

    - name: Build
      run: GOARCH=${{ matrix.arch }} go build -v ./...

    - name: Test
      run: GOARCH=${{ matrix.arch }} go test -v ./...
